# configuration for pre-commit git hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.10
  hooks:
    - id: ruff  # Linter
      args: [--fix, --exit-non-zero-on-fix]
      exclude: ^tests/
    - id: ruff-format  # Formatter
      exclude: ^tests/
